services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'

  detect-emotions:
    image: 'dreayrt/detect-emotions:latest'
    container_name: 'moodify-detect-emotions'
    restart: 'unless-stopped'
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'

  ocr-service:
    image: 'dreayrt/ocr-service:latest'
    container_name: 'moodify-ocr-service'
    restart: 'unless-stopped'
    ports:
      - '8001:8000'
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'

